#!/bin/sh

# this script performs build submission file

./clean
mkdir -p build
`which buildapp` --output build/run --asdf-path ./src \
	 --load-system icfpc --entry "icfpc:run"
cp install build/
cp -R src/ build/
tar -czf skobochka-`date +"%Y%m%d%H%M%S"`.tar.gz --directory build/ .
